### ISSUE TITLE
Hide header and footer in Reuters mobile app

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/bluprint_graphics-kit#109]
Need to respond to a querystring of `outputType=chromeless` by hiding those components.

ToDo for January. This may be better handled in kit, but starting the conversation here.

**Comment by hobbes7878** [comment]
OK, @pkd2512 I'm gonna ask you to do this. I need a PR that hides the SiteHeader, SiteFooter and Sharer [here](https://github.com/reuters-graphics/bluprint_graphics-kit/blob/master/pages/%2Bpage.svelte#L44-L47) when there's a query param of `outputType=chromeless` in the page request.

You should be able to use the `$page.url` store to check if the condition is true. This has some good examples of using query params client side: https://www.okupter.com/blog/sveltekit-query-parameters#clientside-query-parameters-with-sveltekit. 

I'll review the PR before we pull it in. Thanks!

**Comment by hobbes7878** [comment]
> How would graphics appear differently on the app? Now I see them opening in a webview, the URL of which is the same as our pages. Is there gonna be a change in the system?

FYI, this is for the relaunch of the mobile app, which is happening soon. The app will have its own "shell" for the header and footer, so we only want to display the content from our pages, which is why the query param...

**Comment by MatthewWeberTR** [comment]
It will still open in web view, however, they want all the content they open in web view to look as much like the app as possible, and crucially, they want to remove all links from web view that go to non-app stories, ie: our header/footer/refers on the bottom.

**Comment by pkd2512** [comment]
<img width="1234" alt="image" src="https://github.com/reuters-graphics/bluprint_graphics-kit/assets/7580745/b335a2e3-005d-4367-9773-f833fe51c476">
