### ISSUE TITLE
Create new bluprint for glog

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/bluprint_graphics-kit#113]
My idea is to clone this repo and then make edits for the glog layout, so that remaining kit functions stays the same without having to start from an empty bluprint. @hobbes7878

**Comment by hobbes7878** [comment]
Love it. Start a repo!

**Comment by hobbes7878** [comment]
Finished this last weekend while I was worrying about some breaking news popping up :) : https://github.com/reuters-graphics/bluprint_graphics-glog
