### ISSUE TITLE
Add #main-content id to the main tag

### ISSUE THREAD

**Issue by juruwolfe** [reuters-graphics/bluprint_graphics-kit#122]
Can we add "main-content" as an id to <main> tag? This is so if/when you accept my PR in components to add a skip link to the site header (which matches reuters.com), it works as intended and jumps down to main. 

(I can do this as a PR if you'd prefer)

**Comment by hobbes7878** [comment]
Handled in https://github.com/reuters-graphics/graphics-components/pull/181
