### ISSUE TITLE
add d3-selection to package.json?

### ISSUE THREAD

**Issue by MinamiFunakoshiTR** [reuters-graphics/bluprint_graphics-kit#29]
Because categorical chart module is now part of the boilerplate, I think we need to add d3-transition to package.json. Running yarn add d3-selection fixed the issue for me and i was able to create a preview

**Comment by hobbes7878** [comment]
Noticing now we don't have any chart modules as part of the boilerplate. I also think this is only an issue for charts that haven't upgraded to d3 7.0+, which is where we should probably put our effort.
