### ISSUE TITLE
Failing to automatically create a TR repo for new project

### ISSUE THREAD

**Issue by deaxmachina** [reuters-graphics/bluprint_graphics-kit#48]
Failing to automatically create a new TR GitHub repo for new project. 
Prasanta is having the same issue. We checked for credentials in keychain and they seem to be there and correct. My key shouldn't be expired as I created it < 2 months ago. 
<img width="719" alt="Screenshot 2022-01-14 at 09 21 36" src="https://user-images.githubusercontent.com/17324845/149517996-d43ddf91-3806-4797-95fc-32604da3ed88.png">

**Comment by hobbes7878** [comment]
OK. I'll check this out today. For reference, this is the code that's failing: https://github.com/reuters-graphics/graphics-bin/blob/master/src/commands/create-repo/getToken.js

**Comment by hobbes7878** [comment]
After rooting around a bit on my own, finally realised my own token had been deauthorised for access to TR. Once I reactivated that auth, I was able to create a repo using my current token.

@deaxmachina Can you confirm your token is still authorised, e.g., your Configure SSO should look like mine here:

![image](https://user-images.githubusercontent.com/2772078/149525000-37df09d9-d137-49ab-b158-8e491b068660.png)

**Comment by hobbes7878** [comment]
Troubleshot and code appears fine, fine
