### ISSUE TITLE
W3C markup validation

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/bluprint_graphics-kit#59]
It's a good practice to have websites that pass W3C validation. Helps with cross-platform compliance, accessibility and SEO

Nice to have - 
* Check and [validate existing markup](https://validator.w3.org/) 
* Add a [validator in the workflow](https://www.npmjs.com/package/node-w3c-validator) to show warnings and errors 
* Make grammatically correct coding easier

Sample from one of our web pages built with sveltekit
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/7580745/154633394-02c4cae4-6ecc-41e5-af19-881a90885866.png">

**Comment by hobbes7878** [comment]
I hear this, but we're limited to how SvelteKit creates the markup from our components. Their conventions trump ours because we're using their tool. That said if there are any major issues, we want to identify them specifically and make tickets on SvelteKit's repo for them to address.

**Comment by pkd2512** [comment]
I see. So, as you can see in the preview, some of those errors appear in the meta tags, terminated by a fatal error. While I am unsure how it affects the page, however, some of them might just be about fixing some meta props etc. Will do some more audit and get back
