### ISSUE TITLE
Cross platform testing practices

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/bluprint_graphics-kit#60]
It's a good practice to test all our projects on different browsers, devices and OS. Plans to integrate it into people's workflows. 
* Maybe as a checkpoint before publish
* Also, test the embed versions locally

I have used [BrowserStack](https://www.browserstack.com/) in the past, but the free plan comes with its limits. Recently I tried [LambdaTest](https://www.lambdatest.com/) which is free and worked fine.

**Comment by hobbes7878** [comment]
I'm sending this back to you, my friend. I want you to tell me _how_ we could wire this in as part of our publishing process. Is there a GitHub Action ci/cd workflow? Is it a new CLI preview option? What?

Ok, I am also willing to pay a reasonable monthly fee to add this to our process, so find me the best service that's the easiest to integrate into our existing pipeline.

Write me back here with how it would all work and then we can talk about implementing code.

**Comment by hobbes7878** [comment]
Closing for now. We do have chromatic installed on the graphics-components repo, which hopefully helps with some of this.
