### ISSUE TITLE
share card question

### ISSUE THREAD

**Issue by travishartman** [reuters-graphics/bluprint_graphics-kit#61]
i'm seeing this share card path in the archieML doc: 

`ShareImgPath: images/reuters-graphics.jpg`

It's been a hot minute since i've pubbed a thing and seems like we used to name sharecards **share-card.jpg**, but curious now if this default is a templated name (i.e. we should save sharecards with the name reuters-graphics.jpg and overwrite) or do we simply change the path in the doc? and if the latter, why not change the doc to read 

`ShareImgPath: images/share-card.jpg`

?

**Comment by hobbes7878** [comment]
Oh, and it's set to that `reuters-graphics.jpg` cause that's a default image we include in kit when you start up, but always presumed you'd add your own share card and rewrite that path. Also valid to just replace the image, too, and leave the path. The world is yours.
