### ISSUE TITLE
Reduce starter boilerplate

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/bluprint_graphics-kit#69]
Starting a discussion here been meaning to have for a minute.

Have gotten a few bits of feedback that folks would like to start with more minimal boilerplate for the google doc and starter code in the kit, and I think it's probably right.

Out of the box, I think the kit should be wired to cover fast breaking news _first_. From there, adding more complex components should be an exercise in going to the graphics components docs and copying an example from the demo page, where we also include examples of setting props through an ArchieML doc.

So the open question is what's the minimum content that should be in a fresh page. I'd suggest:

- [ ] Headline component
- [ ] BodyText
- [ ] Ai2svelte
- [ ] BodyText
- [ ] Endnotes & referrals

I'd also like to get rid of the string import of the Ai2svelte component. The theory was folks could layout a page completely in google docs, but it creates a lag on the page if the component is above the fold because it has to be imported as a separate script after the app initialises, so I end up having to train everyone to do it in Page.svelte anyway..  

Tagging in @MinamiFunakoshiTR @man-shar @fcage @pkd2512  if any of you have other thoughts.

**Comment by man-shar** [comment]
also tagging @AnandKatakamTR if he has ideas.

**Comment by AnandKatakamTR** [comment]
No ideas off the top of my head, but would really like to hit the ground running fast in terms of pushing out a page. 

This is more workflow, but how do we have version control for assets would be helpful.

**Comment by hobbes7878** [comment]
So if by assets you mean AI graphics that is a place where we've pushed hard to move _everything_ in git so the whole thing is more easily shared between folks working on the same project.

Two pain points still exist:
1. If the AI file is larger than 100MB then we can't share it through github. Only option currently is OneDrive and manually pass those AI files around. I get the sense this is a little rarer these days (since Marco left?? :P ).
2. If 2 or more people are working on the same AI file _concurrently_, git can not reconcile the differences between people's work in the same file. This also pretty rare, I think. If more than 2 people are working, they tend to pick up where the other left off, so that concurrency isn't an issue and it actually works better to have the AI files in github to push changes back and forth.

**Comment by MinamiFunakoshiTR** [comment]
the list of boilerplate components look good to me
