### ISSUE TITLE
GH desktop commit issue about file size check

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/bluprint_graphics-kit#72]
The issue is back at times. @hobbes7878 
<img width="711" alt="image" src="https://user-images.githubusercontent.com/7580745/170367120-c06904ce-31d8-43dd-91b3-999877a0819a.png">

Line 17
<img width="484" alt="image" src="https://user-images.githubusercontent.com/7580745/170367587-56b4fb7d-b965-489e-87dc-be3929f713a0.png">

**Comment by pkd2512** [comment]
@hobbes7878 

The `cd` doesn't work is there is a space in the root directory name. I enclosed the `$repo_root` in quotes but for some reason the fileSize check doesn't work. I added a dummy ai file of 1gb size and tested.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/7580745/178931673-7af6517e-0d20-4cda-a223-705fc5f20e0d.png">

**Comment by hobbes7878** [comment]
I think this is fixed, but feel free to re-open if not.
