### ISSUE TITLE
Questions about the pre-commit hook

### ISSUE THREAD

**Issue by man-shar** [reuters-graphics/bluprint_graphics-kit#90]
I've had this issue with a couple projects.

The sequence of events goes something like:
1. I run `git add .`
2. I commit. And the pre-commit hook starts.
<img width="886" alt="image" src="https://user-images.githubusercontent.com/12295494/187898825-52eb758e-b7cc-42b2-b0ce-f3c2e8f8831a.png">

3. It seemingly runs fine and does it thing.
<img width="998" alt="image" src="https://user-images.githubusercontent.com/12295494/187898961-23117df0-5033-468e-a654-fbb638ba8c78.png">

4. But my git status is back to untracked changes in files.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/12295494/187899045-cfb189e9-7db1-4fe1-be92-af66e087fa2e.png">

I usually "solve" this by continue to git-add and commit till my git is all clean post the pre-commit hook.

I guess my primary question is if this is intentional behaviour?

If so, could multiple people working on the same project face merge issues because there's untracked changes after the hook I might be unaware of? (I wouldn't have bothered with a git status after committing if I didn't have the zsh indicator.)

**Comment by hobbes7878** [comment]
Weird... You're right!

After I moved us from husky to lefthook for git hooks, apparently the behaviour is different. Lefthook doesn't automatically add changed files to the last commit:
https://github.com/evilmartians/lefthook/issues/64

I see a few scattered solutions, so will need to test one and then will add here.

Thanks for out-pointing @man-shar.
