### ISSUE TITLE
ai-Map does not load out of box

### ISSUE THREAD

**Issue by travishartman** [reuters-graphics/bluprint_graphics-kit#94]
Map of Haiti was not loading out of the box- yarn start with the unadulterated code and nothing showed up - copied code in from bottom of graphicblock from [component link](https://reuters-graphics.github.io/graphics-components/iframe.html?viewMode=docs&id=components-graphicblock--ai-2-svelte#ai2svelte) to overwrite code from screenshot in app.svelte
replaced this:
![Screen Shot 2022-09-16 at 3 00 19 PM](https://user-images.githubusercontent.com/4682934/190712379-90b01f22-011b-42d1-9403-dce86ef96f01.png)
 with this:
`   <MyAiMap assetsPath="{assets}" />`

map now loads,  would it be possible to streamline the initial offering from GK so no copy paste is needed?

**Comment by hobbes7878** [comment]
Arg. Yep, confirmed. Will sort this out. Apologies for delay.
