### ISSUE TITLE
Batch ai2svelte run for all gfx in project-files

### ISSUE THREAD

**Issue by man-shar** [reuters-graphics/bluprint_graphics-kit#95]
This was a suggestion from @VijdanKawoosaTR while working on his recent Arctic project.

We could add a command for a batch ai2svelte run for all gfx in project-files, similar to the statics rig.

I can take this one, but was wondering if any issues that I am not foreseeing?

Adding @hobbes7878 @AditiBhandariTR @pkd2512 @fcage

**Comment by pkd2512** [comment]
Can be a useful feature. One thing to note is that oftentimes there are dummy/backup files that we don't want to export. So, it might be useful to still provide a selectable (or deselectable) list of files to pick for export in the CLI.

**Comment by man-shar** [comment]
great point!

**Comment by pkd2512** [comment]
Another use of the feature in the future - 
1. Make sure the latest export code is used, w/o having the user download the js file and save it in illustrator scripts
2. Can have multiple scripts - say we want to separate settings for exports for page vs export for statics, some custom font settings, or whatever.
